# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 943639469aa12238577fff8ce47e79ba37077461559abc1483cbe1d9d316f1595cb75c5e977fccb4c0ff149aba845741b6f477d8b8f6954c69708cd7217b59fe

test:
  secret_key_base: 24e3e9218af197a031a3a3f00c55020cb11440e9a2142ba822d5490ccad8223792383244215db27bc914b024d748bb3a279c6c70b8fb8812cb9de4f9bea2f332

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
